### ISSUE TITLE
Move to default HTTPS port

### ISSUE THREAD

**Issue by rusekjf** [Filirom1/photobooth#1]
https://github.com/Filirom1/photobooth/blob/8bb6a3de361f78614ca77175fc5144ed0d1094cc/photobooth.go#L115
Need to be replaced by `port = "443"`
Thanks! ;)

**Comment by Maarc-D** [comment]
Can not believe it's not a var we can override at run time ;) (or using environment variable :p )

**Comment by Filirom1** [comment]
Contribution are welcomed :-P

**Comment by Filirom1** [comment]
Port can be defined via the environment variable: `PORT`.
For http (instead of https), you can define `DISABLE_TLS`
